// Build mode — hardened (packaged release) vs development (unbundled run).
//
// A packaged release build is HARDENED; `pnpm dev`, the browser preview, and any
// unbundled run are DEVELOPMENT. This is the wallet's own concept, and it backs
// four laws:
//
//   1. Egress allowlist ≡ dial-set. The packaged webview CSP (tauri.conf.json)
//      is GENERATED by scripts/gen-csp.mjs from the same SDK registry the
//      runtime dials, plus the pinned static hosts. The CSP is never hand-edited;
//      a fleet-membership change means regen + rebuild.
//   2. Known-endpoint dial law. Endpoint selection honours only the known set
//      (see isKnownEndpoint in client.ts); a persisted out-of-set selection
//      falls back to the default. This runs on every boot regardless of
//      developer mode — the UI gate is never the enforcement point.
//   3. Compound gate for trust-widening tooling. Any future surface that widens
//      egress or trust (custom RPC endpoints, custom chains) requires
//      `!isHardenedBuild() && developerMode`; a hardened build may only
//      reorder/pin/subset the canonical fleet.
//   4. Honest dev-build self-description. Surfaces that cannot work outside a
//      packaged build say so plainly, never erroring and never pretending (the
//      About "Update" row's "development build" state is the model).

/** True for a packaged release build (Vite PROD); false for any unbundled run. */
export function isHardenedBuild(): boolean {
  return import.meta.env.PROD === true;
}
