// Passkey credential — on-disk shape persisted inside `VaultRecord`.
//
// Wire format (JSON, lives inside the vault container next to the
// existing wrapped_vek + sealed_payload fields):
//
//   {
//     "id":            "<b64u, 16 bytes credential id>",
//     "backend":       "software",
//     "public_key":    "<b64u, 32 bytes Ed25519 pubkey>",
//     "sealed_secret": { "nonce": "<b64u>", "ciphertext": "<b64u>" },
//     "counter":       0,
//     "label":         "MacBook Touch ID",
//     "device_name":   "MacBook Pro 14\"",
//     "created_at":    1735689600,
//     "last_used":     1735689600
//   }
//
// Sizes:
//   id              — 16 bytes random (collision-free per-vault for the
//                     life of the wallet; matches WebAuthn `rawId` typical
//                     authenticator output)
//   public_key      — 32 bytes Ed25519 (CompressedY-encoded)
//   sealed_secret   — 32-byte Ed25519 secret + 16-byte GCM tag, sealed
//                     under the vault's VEK with a fresh 12-byte nonce
//   counter         — u32 monotonic — incremented on every successful
//                     assertion (replay protection per WebAuthn level-2)

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use rand::{rngs::OsRng, RngCore};
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::vault_multi::container::SealedPayload;

/// Length of the credential id. 16 random bytes = 128 bits, plenty
/// for collision-free per-vault uniqueness without bloating the
/// container with longer base64 strings.
pub const CREDENTIAL_ID_LEN: usize = 16;

/// Ed25519 public-key length. Pinned here so the deserializer can
/// reject malformed records.
pub const ED25519_PUB_LEN: usize = 32;

/// Ed25519 secret-key length (the seed, not the expanded form).
pub const ED25519_SEC_LEN: usize = 32;

/// Maximum credentials per vault. Matches the browser-wallet cap
/// (`MAX_CREDENTIALS_PER_VAULT = 8`): a user with Windows Hello,
/// Touch ID, a YubiKey, and a TPM-backed software credential is at
/// 4; 8 leaves headroom without bloating the container.
pub const MAX_PASSKEYS_PER_VAULT: usize = 8;

/// Source of the secret-key material backing this credential.
///
///   - `Software`  — Ed25519 secret generated by the wallet, sealed
///                   under the vault's VEK. The only backend
///                   Phase 8 ships. Defaults via `#[serde(other)]` so
///                   future variants land as data-only changes.
///   - (future)    — `OsPlatform` for OS-managed credentials whose
///                   secret material lives in the OS keychain /
///                   secure enclave (no `sealed_secret` on disk).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum PasskeyBackend {
    #[default]
    Software,
}

/// Persisted passkey credential. Lives inside `VaultRecord.passkeys`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PasskeyEntry {
    /// base64url-no-pad encoded 16-byte credential id.
    pub id: String,
    /// Backend that produced this credential. Phase 8 = always
    /// `Software`; future OS-backed credentials carry their own tag.
    #[serde(default)]
    pub backend: PasskeyBackend,
    /// base64url-no-pad encoded 32-byte Ed25519 public key.
    pub public_key: String,
    /// AEAD-sealed 32-byte Ed25519 secret. `None` for OS-backed
    /// credentials whose secret never leaves the OS authenticator —
    /// always `Some(..)` for the Software backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sealed_secret: Option<SealedPayload>,
    /// Monotonic counter — incremented on every successful assertion.
    /// Replay protection: a captured assertion can't be replayed
    /// because the verifier rejects any counter ≤ the stored value.
    #[serde(default)]
    pub counter: u32,
    /// User-editable label. 1-64 chars after trim. "My laptop Touch
    /// ID", "YubiKey blue", etc.
    pub label: String,
    /// Optional device name pulled from the OS at enrollment time
    /// (best-effort hostname; `None` if unavailable).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_name: Option<String>,
    /// UNIX seconds at enrollment.
    pub created_at: u64,
    /// UNIX seconds of the most recent successful assertion. Equal to
    /// `created_at` until the credential is first used.
    pub last_used: u64,
}

impl PasskeyEntry {
    /// UI-facing summary (no secret material, no sealed_secret
    /// shape). Returned by `list_passkeys` to the TS SDK.
    pub fn summary(&self) -> PasskeyEntrySummary {
        PasskeyEntrySummary {
            id: self.id.clone(),
            backend: self.backend,
            public_key: self.public_key.clone(),
            label: self.label.clone(),
            device_name: self.device_name.clone(),
            counter: self.counter,
            created_at: self.created_at,
            last_used: self.last_used,
        }
    }
}

/// Public-facing summary handed to the UI. Carries the pubkey so the
/// UI can surface "this credential signed with key X" but never the
/// sealed secret.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PasskeyEntrySummary {
    pub id: String,
    pub backend: PasskeyBackend,
    pub public_key: String,
    pub label: String,
    pub device_name: Option<String>,
    pub counter: u32,
    pub created_at: u64,
    pub last_used: u64,
}

/// Errors specific to the passkey layer. Wrapped by the Tauri command
/// surface into `VaultError`-style typed errors at the boundary.
#[derive(Debug, Error, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "code", rename_all = "snake_case")]
pub enum PasskeyError {
    #[error("vault not found")]
    VaultNotFound,
    #[error("credential not found")]
    CredentialNotFound,
    #[error("credential limit reached ({max} per vault)")]
    LimitReached { max: usize },
    #[error("invalid label (must be 1-64 chars after trim)")]
    InvalidLabel,
    #[error("credential payload malformed")]
    Malformed,
    #[error("removing the last passkey while policy demands one is blocked")]
    LastPasskeyBlocked,
    #[error("internal crypto error")]
    Crypto,
}

/// Generate a fresh random credential id (16 bytes).
#[must_use]
pub fn generate_credential_id() -> [u8; CREDENTIAL_ID_LEN] {
    let mut buf = [0u8; CREDENTIAL_ID_LEN];
    OsRng.fill_bytes(&mut buf);
    buf
}

/// base64url-no-pad encode a credential id.
#[must_use]
pub fn encode_credential_id(id: &[u8; CREDENTIAL_ID_LEN]) -> String {
    URL_SAFE_NO_PAD.encode(id)
}

/// Decode a credential id back to raw bytes. Returns `Malformed` on
/// bad base64 or wrong length.
pub fn decode_credential_id(s: &str) -> Result<[u8; CREDENTIAL_ID_LEN], PasskeyError> {
    let bytes = URL_SAFE_NO_PAD
        .decode(s)
        .map_err(|_| PasskeyError::Malformed)?;
    if bytes.len() != CREDENTIAL_ID_LEN {
        return Err(PasskeyError::Malformed);
    }
    let mut out = [0u8; CREDENTIAL_ID_LEN];
    out.copy_from_slice(&bytes);
    Ok(out)
}

/// Validate a user-supplied label. Rejects empty / whitespace-only /
/// too-long strings.
pub fn validate_label(label: &str) -> Result<String, PasskeyError> {
    let trimmed = label.trim();
    if trimmed.is_empty() || trimmed.len() > 64 {
        return Err(PasskeyError::InvalidLabel);
    }
    Ok(trimmed.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn credential_id_round_trips_through_base64() {
        let id = generate_credential_id();
        let s = encode_credential_id(&id);
        let decoded = decode_credential_id(&s).unwrap();
        assert_eq!(decoded, id);
    }

    #[test]
    fn credential_id_rejects_bad_base64() {
        assert_eq!(
            decode_credential_id("!!not-valid!!").unwrap_err(),
            PasskeyError::Malformed
        );
    }

    #[test]
    fn credential_id_rejects_wrong_length() {
        let s = URL_SAFE_NO_PAD.encode([0u8; 8]);
        assert_eq!(decode_credential_id(&s).unwrap_err(), PasskeyError::Malformed);
    }

    #[test]
    fn validate_label_accepts_normal_strings() {
        assert_eq!(validate_label("My laptop Touch ID").unwrap(), "My laptop Touch ID");
        assert_eq!(validate_label("  spaces  ").unwrap(), "spaces");
    }

    #[test]
    fn validate_label_rejects_empty_and_long() {
        assert_eq!(validate_label("").unwrap_err(), PasskeyError::InvalidLabel);
        assert_eq!(validate_label("   ").unwrap_err(), PasskeyError::InvalidLabel);
        let long = "x".repeat(65);
        assert_eq!(validate_label(&long).unwrap_err(), PasskeyError::InvalidLabel);
    }

    #[test]
    fn summary_excludes_sealed_secret() {
        let entry = PasskeyEntry {
            id: "abc".into(),
            backend: PasskeyBackend::Software,
            public_key: "pub".into(),
            sealed_secret: Some(SealedPayload {
                nonce: "n".into(),
                ciphertext: "c".into(),
            }),
            counter: 5,
            label: "lab".into(),
            device_name: Some("host".into()),
            created_at: 100,
            last_used: 200,
        };
        let summary = entry.summary();
        let s = serde_json::to_string(&summary).unwrap();
        assert!(!s.contains("sealed_secret"));
        assert!(!s.contains("ciphertext"));
        // Public material is present.
        assert!(s.contains("\"public_key\":\"pub\""));
        assert!(s.contains("\"label\":\"lab\""));
    }

    #[test]
    fn backend_defaults_to_software_when_missing() {
        let json = serde_json::json!({
            "id": "abc",
            "public_key": "pub",
            "label": "lab",
            "created_at": 100,
            "last_used": 200,
        });
        let entry: PasskeyEntry = serde_json::from_value(json).unwrap();
        assert_eq!(entry.backend, PasskeyBackend::Software);
        assert_eq!(entry.counter, 0);
    }

    #[test]
    fn entry_round_trips_through_json() {
        let entry = PasskeyEntry {
            id: "abc".into(),
            backend: PasskeyBackend::Software,
            public_key: "pub".into(),
            sealed_secret: Some(SealedPayload {
                nonce: "n".into(),
                ciphertext: "c".into(),
            }),
            counter: 1,
            label: "lab".into(),
            device_name: None,
            created_at: 100,
            last_used: 100,
        };
        let s = serde_json::to_string(&entry).unwrap();
        let decoded: PasskeyEntry = serde_json::from_str(&s).unwrap();
        assert_eq!(decoded.id, entry.id);
        assert_eq!(decoded.counter, entry.counter);
        assert_eq!(decoded.label, entry.label);
    }
}
